name: movie_ticket_booking_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  iconsax: ^0.0.8
  get_it: ^8.0.3
  http: ^1.2.2
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  get_storage: ^2.1.1
  get: ^4.6.6
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  form_validation: ^3.2.0
  lottie: ^3.3.1
  connectivity_plus: ^6.1.2
  firebase_storage: ^12.4.0

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  barcode_widget: ^2.0.4
  cloud_firestore: ^5.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/on_boarding_images/
    # - assets/images/animations/
    # - assets/logos/
    # - assets/icons/categories/
    # - assets/images/banner/
    # - assets/images/products/
    - assets/images/user/
    # - assets/images/reviews/
    - assets/icons/payment_methods/

  fonts:
    - family: Oleo
      fonts:
        - asset: assets/fonts/OleoScript-Bold.ttf
          weight: 600
        - asset: assets/fonts/OleoScript-Regular.ttf
          weight: 500
        # - asset: assets/fonts/Poppins-Italic.ttf
        #   style: italic
        # - asset: assets/fonts/Poppins-Medium.ttf
        #   weight: 500
        # - asset: assets/fonts/Poppins-MediumItalic.ttf
        #   weight: 500
        #   style: italic
        # - asset: assets/fonts/Poppins-SemiBold.ttf
        #   weight: 600
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Italic-VariableFont.ttf
        - asset: assets/fonts/NotoSans-VariableFont.ttf
          weight: 700

# flutter_native_splash:
#   color: "#ffffff" # Replace with your desired splash background color
#   image: assets/logos/t-store-splash-logo-white.png # Replace with the path to your splash screen image
#   android: true
#   ios: true
#   web: false
